### ISSUE TITLE
Logo video

### ISSUE THREAD

**Issue by larsbrinkhoff** [logothings/logothings.github.io#1]
Hello,

Here is a Logo video from MIT:  
http://projects.csail.mit.edu/video/history/aifilms/25-logo.mp4

Which graphical display is used at the end?

**Comment by walterbender** [comment]
I only saw the teletype output in this video. Was there a different video with more?

**Comment by larsbrinkhoff** [comment]
Thanks for checking!

The graphical stuff is at the end.  There's a segment with circles at around 7-8 minutes, and at 8:30 begins another segment with colored dots.

**Comment by larsbrinkhoff** [comment]
By the way, maybe I should explain the background for my question.  I'm preserving and restoring software from the MIT Incompatible Timesharing System.  I'm encountering many files from the MIT Logo group.  Among those are programs that refer to the Knight display for the PDP-11/45.  I have been looking at Logo videos to see if I can identify a Knight display, but I don't know what it should look like other than the fact that it was a vector display.  But then, there was also the General Turtle 2500 vector display, so I don't know which is which.

**Comment by walterbender** [comment]
I asked Cynthia to take a look at this a while ago. I'll ask her again.
@cynthiaso

**Comment by larsbrinkhoff** [comment]
Thank you very much.

FYI, there's a chance the old 11LOGO could be restored and run in a PDP-11 emulator.

**Comment by walterbender** [comment]
Maybe contact Brian Silverman? He and his brother are very much into these sorts of restorations.

**Comment by larsbrinkhoff** [comment]
Yes, I have tried to send messages to the email addresses I have found, but I never heard anything back.
