### ISSUE TITLE
Logo Memo Links don't work

### ISSUE THREAD

**Issue by seanjensengrey** [logothings/logothings.github.io#2]
Referenced here, https://logothings.github.io/logothings/Papers.html

And a more complete list here, http://web.sonoma.edu/users/l/luvisi/logo/logo.memos.html

It looks like MIT shutdown ftp://publications.ai.mit.edu

I am specifically looking for the files under ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-246.pdf

I'll try following up with ai.mit.edu

**Comment by seanjensengrey** [comment]
If one does a search for **"aim-246"** (including quotes) such as https://dspace.mit.edu/search?scope=%2F&query=%22aim-246%22&rpp=10&sort_by=0&order=DESC&submit=Go

It will return the new location on dspace, https://dspace.mit.edu/handle/1721.1/5834

**Comment by walterbender** [comment]
Thanks for pointing out the stale link. I just fixed them all.

**Comment by seanjensengrey** [comment]
I updated the list of logo memos from the  sonoma.edu site here, https://gist.github.com/seanjensengrey/7526857ff08f7c106d5b69afca6a5bcb

**Comment by walterbender** [comment]
@cynthiaso  shall we include (or link to) this list?
